sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: EQ52fqif01Gf9KdPwTUTUnDgPk7TedRm+K0tDvqCmXA3ovYl018kOs0umHiZ7x+syEurECQDrsSh2OwQBcuQSGFZtx6XJlNYhRluDVIwlrp5jLJu/tRBYCfW0E+dO8RhUJjjmhImfJHIb6wFMXgBig/Ryr7V2A+UcmI9OgeTz2lUsvWy0fy8H5mloK/XrZ1uwgDWVf6PeRfPcjLlw576HsUdD9Oc1rQ9KBUzalgLAhecsMjONogBcY3tFs84l5lFzie2poONOU3r6dphfyiNosEgfywqVd5a4IEpIeAHbjFtEI+WtbALr8ss8GNl1dPrcvK1JSw/Pyg07k+J3rjfxXu/eBPEqWhOoGzx0muxZ2AtO7U1zXFUufA1RRrDUWLBkXpSmWNjEtbKp++q9Q0i2zGk7LTL0YH49fP5it7gQSP4BxVSEmRTNJkBqWQR64V+VbtLUTvw6ZwQLMT2CN6blhG2YA4v+jjHE8EIZqw9PZkeRHtcsMSLX+k5sz0ky3Tiw0vE70HjaTuxFWEkxNv2vts66XdrmKxzKh+xSsYalXPAyqdSeRK11aYIyvb4dNj7rhZrwvjJFEk/3M8pw8dbVqhtpwQXXbl6qM9ciaMWWfo3IFGd2qXFodgsLWPEkXdUfp9q0hcZvOkK3B4QakisifKOtVhulGgDAwnirFThLPg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Hunting-Sketches_814
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy